dataset: imagenet
arch: resnet50
workers: 32
epochs: 400
start-epoch: 0
batch-size: 256
learning-rate: 0.03
lr_final: 0.
momentum: 0.9
weight-decay: 1e-4
dim: 128
queue_length: 16384
m: 0.999
T: 0.2
mlp: 1
aug-plus: 1
cos: 1
num-cluster: 3000,2000,1000
warmup-epoch: 20
multi-crop: 0